#[cfg(feature = "board-rev-a")]
mod rev_a;
#[cfg(feature = "board-rev-b")]
mod rev_b;

#[cfg(feature = "board-rev-a")]
pub use rev_a::{
    CAN_BIT_RATE_SWITCHING, CAN_DATA_BITRATE, CAN_NOMINAL_BITRATE, CONFIG_FLASH_LENGTH,
    CONFIG_FLASH_START, EMBASSY_TIME_DRIVER, MUX_RESET_AVAILABLE, REV_A as BOARD,
};
#[cfg(feature = "board-rev-b")]
pub use rev_b::{
    BOARD_TEMPERATURE_SENSOR_ADDRESS, CAN_BIT_RATE_SWITCHING, CAN_DATA_BITRATE,
    CAN_NOMINAL_BITRATE, CONFIG_FLASH_LENGTH, CONFIG_FLASH_START, EMBASSY_TIME_DRIVER,
    MUX_RESET_AVAILABLE, POWER_EXPANDER_ADDRESS, POWER_GATE_SETTLE_MS_PROVISIONAL, REV_B as BOARD,
};
